name: t
  
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  t:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: cmake action
        uses: jwlawson/actions-setup-cmake@v1.14
        with:
          cmake-version: '3.16.x'
      - name: build 
        run: |
          cd t
          cmake -S . -B b -DCMAKE_BUILD_TYPE=Debug
          cmake --build b
          cd b
          make test
          ctest -T memcheck
