name: t
  
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: build 
        run: |
          cd t
          cmake -S . -B b -DCMAKE_BUILD_TYPE=Release
          cmake --build b
          cd b
          make test
